### ISSUE TITLE
{$$} being converted to {~D~D}

### ISSUE THREAD

**Issue by grofit** [showdownjs/showdown#169]
I am porting over from another markdown framework and I was wanting to be able to look for `{$$}blah{/$$}` blah, and I wrote my extensions and regex but was baffled when it was not matching. Upon debugging it appears that the dollars are being changed to ~D... I have not seen this as part of the markdown spec anywhere so was wondering if this is a known thing and why it happens?

I am happy to just use ~D but I just wanted to know why it was happening before I altered the logic.

**Comment by grofit** [comment]
its ok I finally found the Gotchas section.
```
Showdown does the following escape/normalization:

Replaces ~ (tilde) with ~T
Replaces $ (dollar sign) with ~D
Normalizes line endings (\r, \r\n are converted into \n)
uses \r as a char placeholder
```

**Comment by tivie** [comment]
@grofit `RegExp` interprets $ (dollar sign) as a special character when it's in a replacement string so we need to escape it. This happens **before the language extensions are run** so they need to take into account this behavior. In fact, it is needed because language extensions might recursively call `showdown.makeHtml()`.

However, special chars are **unescaped before output extensions are run** so they are "safe" in that regard. =P

This was documented in the source but, as you rightly pointed out, it should be mentioned in the documentation itself.

I've added a paragraph to the extension wiki explaining this: https://github.com/showdownjs/showdown/wiki/Extensions#gotchas
