### ISSUE TITLE
Strange issue with custom extension in Firefox but not in Chrome

### ISSUE THREAD

**Issue by grofit** [showdownjs/showdown#171]
So here is a jsfiddle showing the issue:

https://jsfiddle.net/t6f9yz7y/

If you look at the source in chrome it looks normal, but if you look in firefox it is all garbled, is this a known issue?

**Comment by tivie** [comment]
Yeah, you're right. This is baffling me too.

On latest Safari and Chrome the output is correct.

On IE 11 and Firefox it's broken.

@pdeschen thoughts?

**Comment by tivie** [comment]
Actually, it does not work in ANY browser, the output is just different.

**The problem does not have anything to do with Showdown**... it is caused by a mXSS filter in modern browsers.

Basically, everything you feed to the innerHTML property gets XSS filtered, which your example falls perfectly into.

For instance, you can observe this behaviour without using showdown at all:

[**CODEPEN**](http://codepen.io/tivie/pen/eNMPwg)
```js
  var html = "<a class='some-link' data-bind='click: function(){ someMethod('one', 'two'); }'>two</a>"
  document.getElementById('foo').innerHTML = html;
  console.log(document.getElementById('foo').innerHTML);
```

**Your fiddle showing that showdown's output is correct:** https://jsfiddle.net/06ngvj00/3/

**Comment by grofit** [comment]
Never knew that, I know that knockout allows you to set the html content of an element with this sort of thing so I will go look at see how they do it and see if I can replicate, although its gonna be difficult as I guess all I can do from showdowns perspective is output html, maybe I can use `data-*` attributes to feed my data in and then have a custom binding for linking and see if that works...

Thanks again for your help.
