### ISSUE TITLE
Markdown inside HTML doesn't parse

### ISSUE THREAD

**Issue by SyntaxRules** [showdownjs/showdown#178]
When there is markdown inside of html it doesn't seem to parse.

For example:

```
<div class="alert alert-info">
This is an **awesome** link to another site: [Internal to this website :)](/#/foo-bar).
</div>
```

renders as:

![image](https://cloud.githubusercontent.com/assets/4117657/8789879/de11ec58-2efb-11e5-9d76-a8930a746408.png)

Using showdown v1.2.0.

Was this done by design? Or have we not had a need for it?

**Comment by tivie** [comment]
Actually, according to spec, elements inside html blocks should not be parsed by md engine. It is assumed anything inside an HTML block is already in HTML so it shouldn't need to be parsed.

The original markdown.pl, however, had a way of parsing HTML blocks by "marking" them with `markdown="1"`.

Example:

```
# some markdown

blabla
<div>This is **not parsed**</div>
<div makrdown="1">This is **parsed**</div>
```

This was one of the project's original milestones. However, since no one has requested it yet I haven't thought of a way to implement it.

Do you think this is a important feature?

**Comment by SyntaxRules** [comment]
I would greatly enjoy this feature. My main use case is to be able to decorate markdown to look prettier. But I can understand why the original spec didn't make heavy provisions for it- markdown should be markdown, not markdown with html.

That being said github doesn't support this.

**Comment by rodrigogoncalves** [comment]
@tivie, you say "according to spec". Which spec is that? Is that [CommonMark's](http://spec.commonmark.org/)?

**Comment by tivie** [comment]
@rodrigogoncalves No, the original official spec, https://daringfireball.net/projects/markdown/

**Comment by tivie** [comment]
@SyntaxRules Added the feature just now to develop branch. Mind taking a look?
