### ISSUE TITLE
Certain links with @ symbols and periods break simplifiedAutoLink

### ISSUE THREAD

**Issue by allanhortle** [showdownjs/showdown#204]
type | link | status
------------ | ------------- | ---------
characters between @ and . | http://website.com/img@x2.jpg | broken 
no @|http://website.com/img-x2.jpg|ok
@ but no .|http://website.com/img@x2|ok
@ and . adjacent|http://website.com/img@.jpg|ok

Example: http://showdownjs.github.io/demo/#/http%3A%2F%2Fwebsite.com%2Fimg%40x2.jpg%0A%0Ahttp%3A%2F%2Fwebsite.com%2Fimg-x2.jpg%0A%0Ahttp%3A%2F%2Fwebsite.com%2Fimg%40x2%0A%0Ahttp%3A%2F%2Fwebsite.com%2Fimg%40.jpg

**Comment by tivie** [comment]
Thanks @allanhortle. 

The problem here is the logic used to detect email addresses. 

According to [rfc6531](https://tools.ietf.org/html/rfc6531), in the local part of the email (the part that comes before the @ symbol) the following characters are allowed:
 - Uppercase and lowercase English letters (a-z, A-Z)
 - Digits 0 to 9
 - Characters ! # $ % & ' * + - / = ? ^ _ ` { | } ~
 - Character . (dot, period, full stop) provided that it is not the first or last character, and provided also that it does not appear two or more times consecutively.

This means something like this is a valid email **`website.com/img@x2.jpg`**

Right now, we basically allowed every character in the email's local part. A possible fix is to be explicit email parsing regex.

This will fix **`http://website.com/img@x2.jpg`** but not **`website.com/img@x2.jpg`**, since it's impossible to know if it's an email or a link

**Comment by tivie** [comment]
should be fixed now
