### ISSUE TITLE
Invalid HTML produced by simple lists

### ISSUE THREAD

**Issue by gpapp** [showdownjs/showdown#210]
Resulting HTML tags are not properly nested when using convert.

````js
    converter.makeHtml('* a\n * b\n *  c\n* d\n\n * e');
````

    * a
    * b
     * c
     * d

    * e

translates to

````html
‌<ul>
<li><p>a</p>

<p><ul>
<li>b</li></p>

<p><li>c</li></ul></p></li>

<li><p>d</p>

<ul>
<li>e</li></ul></li>
</ul>
````

which is improperly nested.

This seems to be a marginal case, as it requires two levels of lists, and at least one double line spacing.

I couldn't pinpoint the cases it gives an error, but my best guess, the issue lies within the way the newlines are converted to `<p>` markups in lists.

I'm using showdown 1.2.3

**Comment by tivie** [comment]
I couldn't reproduce the exact output you're getting (neither with showdown latest or v 1.2.3)

[See demo here][1]

[1]: http://localhost:63342/showdown-editor/index.html#/*%20a%0A*%20b%0A%20*%20c%0A%20*%20d%0A%0A*%20e

**Comment by tivie** [comment]
To further add to the answer:

Since v 1.2, showdown applies the following rules to lists:

 1. A list is **single paragraph** if it has only **1 line-break separating items**:

   ```md
    - foo
    - bar
    - baz
   ```
   becomes
   ```html
   <ul>
     <li>foo</li>
     <li>bar</li>
     <li>baz</li>
   </ul>
   ```
   
 2. A list becomes **multi paragraph if ANY of its items is separated by 2 line-breaks**:

   ```md
    - foo
   
    - bar
    - baz
   ```
   becomes
   ```html
   <ul>
     <li><p>foo</p></li>
     <li><p>bar</p></li>
     <li><p>baz</p></li>
   </ul>
   ```

This new ruleset is based on the comments of Markdown's author John Gruber in the [Markdown discussion list][1].

[1]: https://www.mail-archive.com/markdown-discuss@six.pairlist.net/
