### ISSUE TITLE
simplifiedAutoLink + dashes in the URL = unexpected behaviour

### ISSUE THREAD

**Issue by kossnocorp** [showdownjs/showdown#211]
For such code:

``` js
var showdown = require('showdown')
var converter = new showdown.Converter({simplifiedAutoLink: true})
console.log(converter.makeHtml('blah blah https://en.wikipedia.org/wiki/ISO_week_date balh blah blah'))
```

I'm getting:

```
<p>blah blah <a href="https://en.wikipedia.org/wiki/ISO<em>week</em>date">https://en.wikipedia.org/wiki/ISO<em>week</em>date</a> balh blah blah</p>
```

The problem here is that `ISO_week_date` was converted to `ISO<em>week</em>date`.

I tried it on the `HEAD` and on the `v1.2.3`

**Comment by tivie** [comment]
@kossnocorp In order to prevent underscores to be treated as emphasis tags in mid of words you can do one of 2 things:

 1. Escape the underscores with `\`:
    
    ```
    https://en.wikipedia.org/wiki/ISO_week_date`
    ```

 2. Use the option `literalMidWordUnderscores`:

    ```javascript
    var converter = new showdown.Converter({
      simplifiedAutoLink: true,
      literalMidWordUnderscores: true
    })
    ```

You can use the [demo][1] to test

[1]: http://showdownjs.github.io/demo/#/blah%20blah%20https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FISO%5C_week%5C_date%20balh%20blah%20blah

**Comment by kossnocorp** [comment]
@tivie thanks, `literalMidWordUnderscores` works for me!
