### ISSUE TITLE
XSS possible

### ISSUE THREAD

**Issue by treuter** [showdownjs/showdown#216]
It is possible to read the user's cookie, e.g.:
```
[XSS](javascript:window.onerror=alert;throw%20document.cookie)
```

Maybe there should be a configuration option to prevent creating javascript code.

**Comment by tivie** [comment]
Showdown doesn't sanitize the input. This is by design since markdown relies on it to allow certain features to be correctly parsed into HTML. This, however, means XSS injection is quite possible.

Further reference:
 + #57
 + #70 
 + #71 
 + #182 
 + [Markdown's XSS Vulnerability (and how to mitigate it)](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it))

**Comment by treuter** [comment]
Thanks for the information!
