### ISSUE TITLE
Showdown CLI Not Working in OS X or Ubuntu

### ISSUE THREAD

**Issue by sculley4** [showdownjs/showdown#244]
On OS X 10.10.5, Node v4.2.4, npm v2.14.12, after installing showdown globally, running showdown -h returns:
```
env: node\r: Not a directory
```
On Ubuntu 15.10, Node v4.2.4, npm v2.14.12, after installing showdown globally, running showdown -h returns:
```
:  No such file or directory
```
showdown -h works properly on Windows 10, Node v4.2.4 and v5.7.1. Quick google,  it may be related to [windows line endings](https://github.com/npm/npm/issues/2097). 

Hope this can be resolved, thanks.

**Comment by tivie** [comment]
This issue is, in fact, related to npm packaging system that does not convert Windows Line Ending `\r\n` in *nix line endings `\n`.

The git version is working properly.

I'm going to introduce a new step in the packaging to change crlf with lf only.

The next version of showdown's npm package should be fixed.

**Comment by sculley4** [comment]
Thanks very much. Should I close this or you do that?

**Comment by tivie** [comment]
Do not close the issue.
This will be closed automatically when I push the update that fixes it.

**Comment by tivie** [comment]
@sculley4 The issue should be fixed now. Do you mind checking?

**Comment by kevinsimper** [comment]
still not working :(

**Comment by enajeeb** [comment]
I am getting the same error using OS X 10.11.5, node v5.11.1, npm 3.9.5

**Comment by tivie** [comment]
For some reason, building in windows changes the line endings from `/n` to `/r/n`. While git compensates for that, npm does not.

I guess I need to create a VMachine with *nix and publish to npm from there.

The next npm release will have this fixed, I hope.

As a workaround, and until that, replacing line in the cli command should fix the issue.

**Comment by enajeeb** [comment]
Converted line endings of /usr/local/lib/node_modules/showdown/bin/showdown.js to Unix and it works. Thanks for the tip.

**Comment by jeffschwartz** [comment]
I'm running OS X and I can also confirm that changing line ending to lf in node_modules/bin/showdown works for me as well.

**Comment by tivie** [comment]
Ok, I've finally figure out what was happening. Git was globally configured as push:LF, pull: CRLF (as it should on windows environment). I was using my IDE to specifically auto convert CRLF to LF after a pull, since node works just as fine with LF in windows and that should solve the NPM problem.

However, IDE was ignoring what it considered "binary" files, while git wasn't.

**I've published 1.4.2 to NPM and hopefully it is fixed now.**

**Comment by sculley4** [comment]
Just tested briefly in OS X 10.10.5, and it is working. To verify I ran showdown -h and it shows the information properly. Thanks very much.

**Comment by tivie** [comment]
Since it's fixed, I'm closing the issue
