### ISSUE TITLE
Nested ordered / unordered list inconsistent behavior

### ISSUE THREAD

**Issue by tiansh** [showdownjs/showdown#299]
INPUT:

```markdown
* aaa
  1. bbb
```

PERFER:

* aaa
  1. bbb

```html
<ul>
  <li>
    aaa
    <ol>
      <li>
        bbb
      </li>
    </ol>
  </li>
</ul>
```

but got:

```html
<ul>
  <li>
    aaa
  </li>
</ul>
<ol>
  <li>
    bbb
  </li>
</ol>
```

**Comment by tivie** [comment]
[According to the documentation][1], nested elements must have, at least, 3 spaces indentation.

You can [check the demo][2] with your example working 

[1]: https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#nested-lists
[2]: http://showdownjs.github.io/demo/#/a%20list%20with%20indentation%20wrong!%0A%0A*%20aaa%0A%20%201.%20bbb%0A%0A%0Aa%20list%20with%20the%20correct%20indentation!%0A%0A%0A*%20aaa%0A%20%20%201.%20bbb

**Comment by tiansh** [comment]
```markdown
* aaa
  * bbb
```

```markdown
* aaa
  1. bbb
```
But why these two have different behavior?

First one currently been parsed to `<ul><li>aaa<ul><li>bbb</li></ul></ul>`.
But second one is `<ul><li>aaa</li></ul><ol><li>bbb</li></ol>`.

**Comment by tivie** [comment]
You are absolutely right. They should behave exactly the same.

**Comment by tivie** [comment]
should be fixed now in latest development

**Comment by ellatrix** [comment]
@tivie May I ask why it made more sense to be more restrictive to solve the inconsistency, instead of being less restrictive, and allow a minimum of 2 spaces for mixed lists as well?

This less restrictive syntax doesn't seem to clash with any other syntax. Many people seem to prefer only 2 spaces, which makes sense because it is simpler. Github also allows indentation with 2 spaces.

We are using Showdown in the new WordPress editor, Gutenberg. I tried `disableForced4SpacesIndentedSublists`, but it doesn't seem to work, and I see it will be removed from v2.
