### ISSUE TITLE
Italic style regex

### ISSUE THREAD

**Issue by IonicaBizau** [showdownjs/showdown#314]
I want to not turn `hello_beautiful_world` into `<p>hello<i>beautiful</i>world</p>` but considering it a single word, containing `_`.

My use case is when using emojis containing two underscores: `:couple_with_heart:` will be converted into `<p>:couple<i>with</i>heart:</p>`. I just want to have it as `<p>:couple_with_heart:</p>`

How can I configure the regex for italic style?

**Comment by tivie** [comment]
Please take a look at the documentation, wiki or [README.md](https://github.com/showdownjs/showdown/blob/master/README.md#valid-options), namely the option **literalMidWordUnderscores** that does exactly what you're asking for.

**Comment by IonicaBizau** [comment]
Oh, that was simple. Thanks, @tivie! :cake:

**Comment by dgw** [comment]
This thread contains the only mention of "emoji" in the entire repo. :open_mouth:

I take it Showdown doesn't parse or otherwise touch emoji in any way (assuming options like **literalMidWordUnderscores** are set correctly), so a separate emoji parser is needed for e.g. showing proper emoji in GitHub comments? (Hope it's OK to bump this rather than starting a new "issue" that isn't one! :smile_cat:)

**Comment by IonicaBizau** [comment]
@dgw Hey! I'm happy to share with you the project I did at @Bloggify, called [`showdown-emoji`](https://github.com/Bloggify/showdown-emoji). Currently it works for my use-cases––basically it uses the GitHub API Emoji images in the output. :grin: 

Feel free to open issues if you have questions/suggestions/whatever. :rocket: 

Hope it will help others too! :four_leaf_clover:
