### ISSUE TITLE
support custom elements

### ISSUE THREAD

**Issue by petebacondarwin** [showdownjs/showdown#371]
We have HTML code that contains custom block level tags. For example:

```
<code-example>
  ...
</code-example>
```

Currently the `hashHTMLBlocks` sub parser does not capture these as it only matches the built-in block level HTML tags.

**Comment by tivie** [comment]
What do you mean?

**Comment by tivie** [comment]
This input:

```
<code-example>
  ...
</code-example>
```

produces the following html output:

```
<code-example>
  ...
</code-example>
```

**Comment by tivie** [comment]
Ah, you want to prevent showdown from parsing the "contents" of custom blocks?

You need to use a **Lang Extension** or a **Listener Extension** that captures these custom blocks and hashes them

**Comment by petebacondarwin** [comment]
Hi @tivie - thanks for getting back to me so quickly!

Yes, exactly currently the contents is parsed as markdown.

I am indeed currently using a lang extension to workaround this problem, but I believe that it will become increasingly common to have custom elements in our HTML and that support for this should be built in.

If you didn't want to treat all custom elements as block level, one option would be to provide users with a configurable white list of matching element names to check...

**Comment by tivie** [comment]
>I am indeed currently using a lang extension to workaround this problem, but I believe that it will become increasingly common to have custom elements in our HTML and that support for this should be built in.

HTML5 does not support custom elements. XHTML does, however.

> If you didn't want to treat all custom elements as block level, one option would be to provide users with a configurable white list of matching element names to check...

Well, that would make the parser extremely slow since each element added would require to check for balanced tags to make sense of them, effectively turning Showdown into an HTML parser as well.
For simple cases, like `<foo>bar</foo>` it would not be a problem, but complex cases, like:

```xml
<foo>
  <bar>
    <baz>bazinga</baz>
    <baz>bazinga2</baz>
    <bar>blabla</bar>
  </bar>
</foo>
```
would be a nightmare.

Right now Showdown uses some clever tricks to enhance parsing speed. For instance, it separates blocks from spans and does not look for nested block elements inside span elements (as those do not make sense).

Letting users add custom elements would be extremely error prone.

And since extensions are supported, it's actually very simple to make an extension for specific use cases
