### ISSUE TITLE
adding \ before <tag> should render it as "<tag>" and not parse as html

### ISSUE THREAD

**Issue by noformnocontent** [showdownjs/showdown#374]
[source code](https://gist.githubusercontent.com/noformnocontent/44ec7f42064db81bc41cd502f030c681/raw/c45cb4074968d212c30adf0e6cdb4467d68dd0ef/readme.md)
![source code](https://cloud.githubusercontent.com/assets/23745012/24830508/f747193e-1c87-11e7-8b24-f581011f31e5.png)

[how it should be](https://gist.github.com/noformnocontent/44ec7f42064db81bc41cd502f030c681/c45cb4074968d212c30adf0e6cdb4467d68dd0ef)
![how it should be](https://cloud.githubusercontent.com/assets/23745012/24830507/f74341a6-1c87-11e7-8ab8-f5e591ef748d.png)

[how it is now](https://bl.ocks.org/noformnocontent/44ec7f42064db81bc41cd502f030c681/c45cb4074968d212c30adf0e6cdb4467d68dd0ef)
![how it is now on blocks](https://cloud.githubusercontent.com/assets/23745012/24830509/f7473aea-1c87-11e7-8061-c9f768b69dfe.png)

/rel [marked#884](https://github.com/chjj/marked/issues/884)

**Comment by tivie** [comment]
\<foo>**blabla**\</foo>

That's actually a non standard implementation. But since GFM (github) also uses it, we will implement it as a feature.

**Comment by noformnocontent** [comment]
what should be happening here is `\` before any control-symbol turns it to a simple char, and since `tag>` is not a valid html – parser should leave it as text

test :^) :\^)

**Comment by tivie** [comment]
Yes, I know. But, according to the markdown spec, escaping with backslash is reserved for characters that have special meaning in markdown context, not HTML. `<` is a "normal" character to markdown, it has no special meaning.
In markdown, escaping with backslash tells the parser that it should ignore the character and leave it as it is. For example, `\*\*foo\*\*` will be parsed as `**foo**` and not `<strong>foo</strong>`.

There's also the problem with unintended escapes. Example: 'This sentence uses a backslash \<strong>followed by a strong tag</strong>`

However, since GFM supports escaping html entities, this will be implemented as an option.

**Comment by noformnocontent** [comment]
turns out, github has escape for EVERY punctuation symbol as an option: https://github.github.com/gfm/#example-296

likely due to regex smth

**Comment by tivie** [comment]
Yeah, they changed it a bit in favor of commonmark.
