### ISSUE TITLE
makeHtml broken/hangs when called with string containing html tags (v1.7.0) 

### ISSUE THREAD

**Issue by andistuder** [showdownjs/showdown#393]
When calling `makeHtml` with a string containing html markup, the converter seems to hang. 

Example: 

```javascript
const showdown = require('showdown');
const converter = new showdown.Converter();
let html = converter.makeHtml('<p>My<p>');
```

This issue seems to have been introduced with `v1.7.0`. 

Anyone experiencing similar issues?

**Comment by tivie** [comment]
verified. Showdown hangs with malformed HTML. The bug was introduced with the new HTML parser.
I will publish a hotfix as soon as possible



----
We're currently looking to improve showdown with automated tests in all browsers and a proper domain and webpage. If you like our work, please donate!! Your contribution will be greatly appreciated.

https://www.paypal.me/tiviesantos

**Comment by tivie** [comment]
should be fixed now
