### ISSUE TITLE
Suggest That Not Adding Id by Default

### ISSUE THREAD

**Issue by seekei** [showdownjs/showdown#411]
Suggest not adding id by default. In my opinion, the majority of users just wanna convert markdown to html. Keep the basic is just fine. Maybe they can turn it on when they wanna add an id.

**Comment by tivie** [comment]
Although that would make sense, showdown has been adding IDs to headers for a long time and most users rely on that. We try to make as few as possible backwards compatibility changes... only when they are really needed.

Another reason is that the original parser for John Gruber used header ids. Although the original spec didn't specify that, the unofficial original spec (vanilla markdown) is based off the original parser.

Since you can disable them pretty easily with an option, we think disabling headerIds by default would create more confusion than fix any problems users would run into.

**Comment by seekei** [comment]
Thanks for your reply. @tivie

**Comment by tivie** [comment]
Closing this issue. Feel free to reopen the issue if something new arises
