### ISSUE TITLE
[Help] Using strings from an html tag itself

### ISSUE THREAD

**Issue by Lilja** [showdownjs/showdown#421]
Need some help with having the markdown inside an html tag. I've tried the same thing with `marked.js` as well as showdown but I still get the same issue.

Consider the following:

```html
<div id="foo">
  # Hi
</div>
```

and the js
```Javascript
let elem = document.getElementById("foo")

elem.innerHTML = new showdown.Converter().makeHtml(elem.innerHTML)
```

But it still produces 
\# Hi

Instead of 
`<h1>Hi</h1>`

[Here's a jsfiddle ](https://jsfiddle.net/hqL6su4r/)running `showdown.js`  at `1.7.2`

**Comment by Lilja** [comment]
A space before the `#` is the issue.

**Comment by tivie** [comment]
[fiddle](https://jsfiddle.net/87y35baf/)

THis happens because of indentation. As you are aware, markdown is sensitive to indentation. In the provided code, there are two spaces before the `#` symbol. If you remove them, you get the desired result.

```html
<div id="foo">
# Hi
</div>
```

If want/need to keep indentation, showdown might try to remove them for you, if you use the option `smartIndentationFix`. However, this feature is experimental and produces unreliable results.

**Comment by Lilja** [comment]
@tivie Great, thanks for the quick response.
