### ISSUE TITLE
Multiline base64 images support

### ISSUE THREAD

**Issue by alkorgun** [showdownjs/showdown#429]
Hi,

I have some pictures like this:

`
![](data:image/png;base64,iVBORw0KGgoAAAANSUh...)
`

When picture is one-line, showdown works great, but if picture contains line breaks, showdown can't handle that.

Is this a bug or I just missed some option/flag to enable?

P.S. for example [marked.js](https://github.com/chjj/marked) can handle line breaks in images with no problem.

**Comment by tivie** [comment]
According to babelmark2, [almost all parsers (marked included) parse this the same way showdown does.](https://johnmacfarlane.net/babelmark2/?normalize=1&text=!%5Bfoo%5D(data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAAQAAAADCAIAAAA7ljmRAAAAAXNSR0IArs4c6QAAAARnQU1BAA%0ACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAYSURBVBhXYwCC%2F2AAZYEoOAMs8Z%2BBgQEAXdcR7%2FQ1gssAAAAASUVORK5CYII%3D))

**Comment by alkorgun** [comment]
@tivie if you were more attentive, you would see versions: [marked 0.2.6](https://github.com/chjj/marked/releases/tag/v0.2.6) is 5 years old. And so, what is your conclusion? Most of parsers fail, showdown should fail too?

**Comment by tivie** [comment]
@alkorgun As stated [in the original spec](https://daringfireball.net/projects/markdown/syntax#link) links and images urls cannot be wrapped (that is, cannot contain newline characters).

The original spec is silent about this regarding inline link definitions, but explicit in reference style links.

Most Markdown implementations respect the original spec, and do not support linebreaks in urls. Github does not support base64 at all. (either inline or reference)
The ones that do, however, are inconsistent. 

For instance, [marked](https://github.com/chjj/marked) does support linebreaks in inline link definitions, but does not support them in reference style 
([see fiddle](https://jsfiddle.net/2fw2y3mk/))

---

Showdown can implement a special case for base64 encoded images, so that line wrapping is supported.
See the [updated wiki](https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#base64-encoded-images) for more information.
