### ISSUE TITLE
Incorrect conversion of numbered list

### ISSUE THREAD

**Issue by djm158** [showdownjs/showdown#445]
Described this issue [here](https://github.com/BlueHatbRit/mdpdf/issues/32)

Basically, I have a numbered list with some markdown using back ticks in between each item, seen [here](https://raw.githubusercontent.com/laboon/CS1530_Fall2017/master/reading-quizzes/quiz4.md).

When showdown renders the list, each line begins with a 1. rather than displaying in order.

**Comment by tivie** [comment]
You need to indent subblocks 4 spaces

**Comment by tivie** [comment]
# TL;DR;

It's not a bug in showdown, but rather a problem the the input. List's Sub-blocks must be indented 4 spaces (or they will be treated as a "root block")  

# Explanation 
A bunch of things are happening here:

## List's Sub-blocks must be indented 4 spaces 

According to [the original markdown spec][spec] a sub-block, in a list, must be indented to be considered part of the list.

**Example:** ([see showdown's live demo][demo1])

input MD:

    1. Does every software system have an architecture?  Why or why not?
    
        ```
        _________________________________________________________________________
        _________________________________________________________________________
        ```
    
    2. You are designing a climate control system, which accepts inputs from a variety...
    
        ```
        _________________________________________________________________________
        _________________________________________________________________________
        ```

generated HTML:

```html
<ol>
<li><p>Does every software system have an architecture?  Why or why not?</p>
<pre><code>_________________________________________________________________________
_________________________________________________________________________</code></pre></li>
<li><p>You are designing a climate control system, which accepts inputs from a variety...</p>
<pre><code>_________________________________________________________________________
_________________________________________________________________________</code></pre></li>
</ol>
```

In your md source, your code blocks are not indented so each list item is interpreted as  *"new"* list. [see demo][demo2]

This happens in every markdown implementation, even in github's implementation. ([see babelmark2 for comparison in implementations][bb2_1])

```html
<ol>
<li>Does every software system...</li>
</ol>
<pre><code>_____________________________________________________________</code></pre>
<ol>
<li>You are designing a climate control system...</li>
</ol>
```

## The numbering in lists is not important

According to the [same spec][spec]:

> It’s important to note that the actual numbers you use to mark the list have no effect on the HTML output Markdown produces. (...)
> The point is, if you want to, you can use ordinal numbers in your ordered Markdown lists, so that the numbers in your source match the numbers in your published HTML. But if you want to be lazy, you don’t have to.


## Your input "seems" to work in github's

The issue, however, arises when you consider the next paragraph the spec:

> If you do use lazy list numbering, however, you should still start the list with the number 1. At some point in the future, Markdown may support starting ordered lists at an arbitrary number. 

Github supports this *"planned feature"* where the number you in the first list item counts as the starting value of the ordered list. For instance, copy/paste the following markdown in a comment here in github and click preview:

Input:

```md
2. foo
6. bar
2. baz
9. bazinga
```

Output:

2. foo
6. bar
2. baz
9. bazinga

This feature is non standard and not implemented in showdown (although it's planned for a soonish future release),

So, in your MD, every list item is considered a new list, rather than a list item. But since github supports defining the starting number of ordered lists, the output seems correct (although it's not)


[spec]: https://daringfireball.net/projects/markdown/syntax#list
[demo1]: http://showdownjs.github.io/demo/#/1.%20Does%20every%20software%20system%20have%20an%20architecture%3F%20%20Why%20or%20why%20not%3F%0A%0A%20%20%20%20%60%60%60%0A%20%20%20%20_________________________________________________________________________%0A%20%20%20%20_________________________________________________________________________%0A%20%20%20%20%60%60%60%0A%0A2.%20You%20are%20designing%20a%20climate%20control%20system%2C%20which%20accepts%20inputs%20from%20a%20variety...%0A%0A%20%20%20%20%60%60%60%0A%20%20%20%20_________________________________________________________________________%0A%20%20%20%20_________________________________________________________________________%0A%20%20%20%20%60%60%60

[demo2]: http://showdownjs.github.io/demo/#/1.%20Does%20every%20software%20system%20have%20an%20architecture%3F%20%20Why%20or%20why%20not%3F%0A%0A%60%60%60%0A_________________________________________________________________________%0A_________________________________________________________________________%0A%60%60%60%0A%0A2.%20You%20are%20designing%20a%20climate%20control%20system%2C%20which%20accepts%20inputs%20from%20a%20variety...%0A%0A%60%60%60%0A_________________________________________________________________________%0A_________________________________________________________________________%0A%60%60%60

[bb2_1]: https://johnmacfarlane.net/babelmark2/?normalize=1&text=1.+Does+every+software+system+have+an+architecture%3F++Why+or+why+not%3F%0A%0A%60%60%60%0A________________________________________________________________________%0A%0A%60%60%60%0A%0A2.+You+are+designing+a+climate+control+system%2C+which+accepts+inputs+from+a+variety+of+distributed+sensors+(e.g.%2C%0AOf+the+architectural+styles+listed+in+Tsui+_et+al_%2C+which+one+would+be+best+for+this+kind+of+system%3F++Why%3F%0A%0A%60%60%60%0A________________________________________________________________________%0A%0A________________________________________________________________________%0A%60%60%60

**Comment by djm158** [comment]
Ah I see, thanks for the clarification.
