### ISSUE TITLE
Support for GitHub markdown emojis

### ISSUE THREAD

**Issue by KirkMunro** [showdownjs/showdown#448]
GitHub markdown emojis are not supported in showdownjs.

For example:

:bulb: IDEA: Since showdownjs has native GFM support, complete it by adding GFM emoji support to showdownjs!

Please consider adding this natively. I know there is an extension out there, but since GFM is supported natively this really should be there natively too.

**Comment by tivie** [comment]
@KirkMunro Although I see your point, what's the downside of getting that functionality through an extension?

## github way

As far as I can tell, github uses HTML5 custom elements for emojis:

```md
:bulb: IDEA: Since showdownjs has native GFM support, complete it by adding GFM emoji support to showdownjs!
```

```html
<p><g-emoji alias="bulb" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f4a1.png" ios-version="6.0">💡</g-emoji> IDEA: Since showdownjs has native GFM support, complete it by adding GFM emoji support to showdownjs!</p>
```

which won't work for showdown since it would end up generating non compliant HTML5.

## Showdown way

So, if this feature is implemented, we would only replace `:emoji-name:` with the appropriate unicode character and without fallback option.

```md
:bulb: IDEA: Since showdownjs has native GFM support, complete it by adding GFM emoji support to showdownjs!
```

```html
<p>💡 IDEA: Since showdownjs has native GFM support, complete it by adding GFM emoji support to showdownjs!</p>
```

**Comment by tivie** [comment]
Feature implemented in 5b8f1d3 and should be release on v1.8.0.


---

>As you know, ShowdownJS is a free library and it will remain free forever. However, maintaining and improving the library costs time and money. Currently, we're looking to improve showdown with automated tests in all browsers and a proper domain and webpage. 500$ should be enough to to keep showdown testing framework running for a year or two.

**If you like our work and find our library useful, please donate [through Pledgie](https://pledgie.com/campaigns/34908) or directly [through paypal](https://www.paypal.me/tiviesantos)!! Your contribution will be greatly appreciated.**

**Comment by KirkMunro** [comment]
Wow, that was fast. Thanks @tivie!

**Comment by stupidpupil** [comment]
Is it worth noting that this has a relatively large impact on the size of the library? The minimised version grows from around 40kB to 95kB (or 11kB to 32kB after gzipping).

It's not hard to strip this out if you're not interested in emoji-support and want to save the 20-40kB:
```js
.replace(/showdown.helper.emojis = \{[\s\S]+?\};/, 'showdown.helper.emojis = {};');
```
works for me in a grunt-task, for example.

I bring it up only because it might surprise some people using Showdown client-side.

**Comment by stupidpupil** [comment]
Looks as though most of the increase (particularly post-gzip?) is the special :showdown: 'emoji'. It might be possible to slim that down quite a bit.

**Comment by tivie** [comment]
Yeah, the culprits are showdown and octocat emojis.
Showdown emoji was a bit of vanityware.
It can be replaced with an SVG that will reduce the size considerably.
Or maybe remove them altogether.
