### ISSUE TITLE
Anchor point(section_name) defined in markdown file are parsed incorrectly

### ISSUE THREAD

**Issue by nettree** [showdownjs/showdown#451]
Hi,

If we have something in md file like:
```
## Section 1 Headers

<a name="section2"/>

## Section 2 Headers
```
Instead of giving us an output like
```
<h2>Section 1 Headers</h2>

<a name="section2"></a>

<h2>Section 2 Headers</h2>
```
It gives us:
```
<h2>Section 1 Headers</h2>

<a name="section2"></a>

<a name="section2>
<h2>Section 2 Headers</h2>
</a>
```

But if we write `<a name="section2"/>` like `<a name="section2"></a>`, then the result is as expected.

I was wondering, is this behaviour by design or it's a bug?

Thank you.

**Comment by obedm503** [comment]
given that the [`<a>` tag isn't self closing](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a), my guess is that showdown doesn't give it special treatment like actual self closing tags. was the result you posted from showdown directly or from the devtools? I ask because browsers tend to help and close tags that weren't closed

**Comment by tivie** [comment]
@obedm503 is totally right.

`<a>` is not a self closing tag, so your input is invalid HTML. However, showdown just ignores that malformed HTML and leaves it alone as `<a name="section2"/>`.
You can actually see in this ([fiddle](https://jsfiddle.net/tivie/vose4ey9/)) that showdown's output is actually:

```html
<h2 id="section1headers">Section 1 Headers</h2>
<p><a name="section2"/></p>
<h2 id="section2headers">Section 2 Headers</h2>
```

What you're experiencing is probably a browser trying to "fix" your output HTML.
