### ISSUE TITLE
won't work on IE7

### ISSUE THREAD

**Issue by jasper2virtual** [showdownjs/showdown#497]
Error on Array.isArray....  
IE7 not support isArray()  

    showdown.helper.isArray = function (a) {
      'use strict';
      return Array.isArray(a);
    };

Which release of showdown support IE7?

**Comment by aureq** [comment]
@jasper2virtual I think that's probably not a great idea. [IE7](https://en.wikipedia.org/wiki/Internet_Explorer_7) was shipped with Windows XP more than 11 years ago. Since then, Microsoft doesn't support that version nor does it support Windows XP. This means that IE7 is likely to security holes on top of all the features that modern browsers have.

**Comment by jasper2virtual** [comment]
@aureq Yes, you are right, I agree with you. But some of my intranet user is using IE7. ^_^~~~
I am maintaining some intranet pages now, which they are in closed private network.

**Comment by aureq** [comment]
@jasper2virtual Oh I feel your pain! Even in a closed network using IE7/XP is insecure and you should push (and your infosec team too) to have up to date software. Alternatively, running a more recent version of Chrome/Firefox could be an option, but even so the OS would remain insecure.

I highly doubt it will be easy to port showdownjs to IE7. The function `Array.isArray()` has been available since IE9 ([ref](https://www.w3schools.com/jsref/jsref_isarray.asp)) which was shipped with Win7. The technology gap seems quite important...

**Comment by tivie** [comment]
I believe we can work around this in order to make showdown at least somewhat compatible with IE7.

@jasper2virtual Is it the only thing that's breaking in IE7?

**Comment by csvan** [comment]
@jasper2virtual you can provide a polyfill for Array.isArray().

**Comment by priyaarora1989** [comment]
I am also facing same issue on IE8. Is there any update on this request. I am blocked because of this and might have to look out for other parsers.

Is there a workaround for the time being.

**Comment by tivie** [comment]
@priyaarora1989 you can use a polyfill service, like https://polyfill.io/v2/docs/features/ to work around the issue.
