### ISSUE TITLE
[GFM] Extra line breaks

### ISSUE THREAD

**Issue by faressoft** [showdownjs/showdown#602]
I am trying to rendering the same README that is used in
[https://github.com/faressoft/terminalizer](https://github.com/faressoft/terminalizer)

When enabling GFM, extra line breaks added after the shields images
<img width="308" alt="screen shot 2018-10-13 at 1 06 08 pm" src="https://user-images.githubusercontent.com/1908658/46904214-57c48980-cee9-11e8-9bbd-0811c009c23f.png">

The generated HTML

```html
<p><a href="https://github.com/faressoft/terminalizer/blob/master/LICENSE"><img src="https://img.shields.io/npm/l/terminalizer.svg" alt="npm" /></a><br />
<a href="https://gitter.im/terminalizer/Lobby"><img src="https://badges.gitter.im/join_chat.svg" alt="Gitter" /></a><br />
<a href="https://www.youtube.com/watch?v=QH2-TGUlwu4"><img src="https://img.shields.io/badge/nyancat-approved-ff69b4.svg" alt="Unicorn" /></a><br />
<a href="https://goo.gl/QJzJu1"><img src="https://img.shields.io/badge/twitter-share-76abec.svg" alt="Tweet" /></a></p>
```

**Comment by tivie** [comment]
You need to deactivate simpleLineBreaks option after enabling the the github flavor. 

```
var converter = new showdown.Converter();
converter.setFlavor('github');
converter.setOption('simpleLineBreaks', false);
```

**Why?**

Well, because github, for some reason, is inconsistent in how it treats linebreaks. For instance, in comments it treats linebreaks as `<br/>`. (You can try it here in the comment section)

This text
has only
soft breaks

But in reamde.md and other places, it ignores soft linebreaks.

**Comment by faressoft** [comment]
Works fine :) Thanks
