### ISSUE TITLE
URL Text values are being wrapped in angle brackets

### ISSUE THREAD

**Issue by propertunist** [showdownjs/showdown#681]
Hi,
I am finding that when some HTML that I convert using Showdown contains a url (standard formatting), I often find that the resulting markdown has spurious angle brackets within the URL.

## Input
```
<p><a href="https://www.google.com">https://www.google.com</a></p>
```
## Output
```
[https://www.google.com](<https://www.google.com>)
```
## Expected Output
```
[https://www.google.com](https://www.google.com)
```

**Comment by tivie** [comment]
The angle brackets are there to make sure the url is properly delimited, as stated in the spec.

There are some situations where weird HTML will produce malformed markdown. Example: `<a href="http://example.com/some 'weird_url'"></a>`

Instead of working through all variations of these edge cases (and slow down the parser), we wrap them inside angle brackets.

**Comment by propertunist** [comment]
I'm not sure I understand, but I have moved on to using a different parser now - thanks fore responding.
