### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by jorilallo** [showdownjs/showdown#70]
It seems that link and image titles can be abused easily. Here's and example:

    [Poolparty!](http://www.missionmission.org/wp-content/uploads/2013/08/pool-party-560x328.jpg" onmouseover=alert(document.cookie) id=test)

This is prevented on titles but not in urls. Fix is pretty easy:

    url = escapeCharacters(url,"*_");
    url = url.replace(/"/g,"&quot;");

**Comment by tgienger** [comment]
Wouldn't it be better to be more specific with the regular expression? For this particular one I'm using:
```javascript
text = text.replace(/(\[((?:\[[^\]]*\]|[^\[\]])*)\]\([ \t]*()(?:(?:['"])?((?:(?:http|https):\/\/)?(?:[\w\-_]+(?:(?:\.[\w\-_]+)+))(?:[\w\-\.,@?^=%&amp;:\/~\+\!#]*[\w\-\@?^=%&amp;\/~\+#]))['"]?)\))/g, writeAnchorTag);

This doesn't allow spaces at the end of the url or anything between the quote and ending parenthesis.

**Comment by tivie** [comment]
@tgienger @jorilallo  I'm a bit averse to add this kind of protection into the core converters because:

 - I don't think it's not the job of a converter/parser. A converter's output should match the input as closely as possible.
 - This puts the extra burden of assuring security into the library, something I don't feel confident (or competent) enough to do.
 - This does not prevent XSS attacks if showdown is used as a client-side rich text editor (nothing prevents me from inspecting and altering the library in such way that input is no longer escaped).
- This can lead to a false sense of security, because escaping entities is not enough to prevent XSS attacks.
 - Also, since markdown allows pure embeded html tags, Showdown would need to start parsing and escaping those too.
 - npm has a great many number of security libraries and filters that deal with this kind of issues that can be run on Showdown output.

That being said, maybe some simple xss prevention is a good idea.  A couple of approaches come to mind:
 1. Adding some basic XSS escaping that you can activate through options. This can run after the conversions are done and over the produced HTML. We could also provide a way to change the XSS escaping function so that users can run more sophisticated algorithms.
 2. Providing a simple hook system that enables you to switch in place a determined sub converter.
 3. Adding a pre parser that cleans the input directly.

Opinions and feedback are welcome.

**Comment by pdeschen** [comment]
This is definitely not the responsibility of a converter to protect against XSS. I would defer to using a XSS filter on showdown output. See https://github.com/leizongmin/js-xss.

That being said, I think we should add a note about XSS aspects.

**Comment by pdeschen** [comment]
Best way to handle this would be to have a showdown-xss output type extension dealing with such matter. Anyone up to the task? I've added a reference in [Contributing](https://github.com/showdownjs/showdown/wiki/Contributing#extension-requests) wiki page.

Closing for now.

**Comment by markgeraty** [comment]
@pdeschen We just published [showdown-xss-filter](https://github.com/VisionistInc/showdown-xss-filter) to npm using the library you suggested above.  Seems to work great, hope that helps!

**Comment by pdeschen** [comment]
@markgeraty nice! you should add unit test and bower support eventually, with a dep over xss (which is already available within bower)

**Comment by markgeraty** [comment]
Created issues for those - feel free to create an issue for anything else you think we are missing!

**Comment by tivie** [comment]
Awesome! Kudos!

************************************************
Estevão Soares dos Santos

************************************************

2015-05-22 18:38 GMT+01:00 Mark <notifications@github.com>:

**Comment by tivie** [comment]
For more information, please see the wiki page about [Markdown's XSS Vulnerability and how to mitigate it](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it))
