### ISSUE TITLE
Update emoji for github flavor.

### ISSUE THREAD

**Issue by jcs090218** [showdownjs/showdown#821]
Right now some emoji aren't be showing when using `github` flavor. Is there a way to update it? Thanks! 😕

**Comment by marcomontalbano** [comment]
Hi @jcs090218, I just created a PR to update all emojis. Since I suppose that it will take some time to be reintegrated into master I solved this issue in another way in a project of mine.
If you already know which are the emojis that you need, you can do something like this:

```js
import showdown from 'showdown';

showdown.helper.emojis['spiral_calendar'] = '\ud83d\uddd3\ufe0f';

const converter = new showdown.Converter({
  ...
```

Otherwise, If you need them all you can just copy everything from #837 looking at `src/helpers.js`.

```js
import showdown from 'showdown';

showdown.helper.emojis = {
  ...
};
```

I hope this can help you.
