### ISSUE TITLE
Is showdown still maintained?

### ISSUE THREAD

**Issue by jleider** [showdownjs/showdown#833]
There haven't been any updates in nearly a year even though there are plenty of bug reports and open pull requests.

**Comment by tivie** [comment]
Unfortunately, I'm a public health doctor, currently fighting the COVID pandemic, so I don't have much time to maintain showdown. I'm hoping, when all this is over, I can start maintaining this library again.

**Comment by gauravshah27** [comment]
We are also seeing security vulnerabilities because of showdown 1.9.1 because of the transitive yargs dependency 14.2.x which pulls in a vulnerable y18n 4.x dependency. The fix is to move to y18n 5.0.5.

Here is the security vulnerability that we are seeing - https://snyk.io/vuln/SNYK-JS-Y18N-1021887

Here is the tree that I was talking of:
`
showdown@1.9.1
  yargs@14.2.3
    y18n@4.0.0 
`

**Comment by SyntaxRules** [comment]
@tivie I've put a couple of updates into the library. I'll clean things up a bit. Lets chat soon about a 2.0.0 release.

For everyone else, feel free to @mention me on issues I've missed. I haven't been active on this form for a while, so it will take some time for me to work down the blacklog of issues.

**Comment by SyntaxRules** [comment]
Tracked in #881
